#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm neovim nodejs npm

sudo npm install -g @olrtg/emmet-language-server
sudo npm install -g vscode-langservers-extracted
sudo npm install --save-dev --save-exact prettier@3.9.6
